term.clear()

shell.run("rm egde/*")
shell.run("rm startup.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/menu.lua egde/menu.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/eggshell.lua egde/eggshell.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/egdia.lua egde/egdia.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/assets/sat.nfp egde/assets/sat.nfp")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/assets/sat2.nfp egde/assets/sat2.nfp")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/eggshells/help.lua egde/eggshells/help.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/eggshells/time.lua egde/eggshells/time.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/assets/button1.nfp egde/assets/button1.nfp")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/settings.lua egde/settings.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/startup.lua startup.lua")
sleep(1)
os.reboot()
