term.clear()

shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/menu.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/eggshell.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/egdia.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/assets/sat.nfp")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/assets/sat2.nfp")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/eggshells/help.lua")
shell.run("wget https://github.com/HambatEverett/EGDE-Mobile/raw/refs/heads/main/egde/eggshells/time.lua")
shell.run("wget")
sleep(1)
os.reboot()
